# git clone https://github.com/academiaonline/phpinfo
# cd phpinfo/
# git checkout 2021-10
# kubectl create ns phpinfo
# kubectl create cm phpinfo-cm --from-file ./src/index.php --namespace phpinfo
# kubectl apply --filename kube-compose.yaml --namespace phpinfo
# kubectl get all --namespace phpinfo
# kubectl logs phpinfo-po --namespace phpinfo

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: phpinfo
    version: 2021-10
  name: phpinfo-po
spec:
  containers:
    -
      args:
        - -f
        - src/index.php
        - -S
        - 0.0.0.0:8080
      image: academiaonline/phpinfo:2021-10
      name: phpinfo-container
      ports:
        - 
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
  volumes:
    -
      configMap:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
      name: phpinfo-volume
      
            
  
